<?php
declare(strict_types=1);

// HubspotAnalytics SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotAnalyticsUtility::setRegistrar(function (HubspotAnalyticsUtility $u): void {
    $u->clean = [HubspotAnalyticsClean::class, 'call'];
    $u->done = [HubspotAnalyticsDone::class, 'call'];
    $u->make_error = [HubspotAnalyticsMakeError::class, 'call'];
    $u->feature_add = [HubspotAnalyticsFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotAnalyticsFeatureHook::class, 'call'];
    $u->feature_init = [HubspotAnalyticsFeatureInit::class, 'call'];
    $u->fetcher = [HubspotAnalyticsFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotAnalyticsMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotAnalyticsMakeContext::class, 'call'];
    $u->make_options = [HubspotAnalyticsMakeOptions::class, 'call'];
    $u->make_request = [HubspotAnalyticsMakeRequest::class, 'call'];
    $u->make_response = [HubspotAnalyticsMakeResponse::class, 'call'];
    $u->make_result = [HubspotAnalyticsMakeResult::class, 'call'];
    $u->make_point = [HubspotAnalyticsMakePoint::class, 'call'];
    $u->make_spec = [HubspotAnalyticsMakeSpec::class, 'call'];
    $u->make_url = [HubspotAnalyticsMakeUrl::class, 'call'];
    $u->param = [HubspotAnalyticsParam::class, 'call'];
    $u->prepare_auth = [HubspotAnalyticsPrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotAnalyticsPrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotAnalyticsPrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotAnalyticsPrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotAnalyticsPrepareParams::class, 'call'];
    $u->prepare_path = [HubspotAnalyticsPreparePath::class, 'call'];
    $u->prepare_query = [HubspotAnalyticsPrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotAnalyticsGraphql::class, 'body'];
    $u->graphql_errors = [HubspotAnalyticsGraphql::class, 'errors'];
    $u->result_basic = [HubspotAnalyticsResultBasic::class, 'call'];
    $u->result_body = [HubspotAnalyticsResultBody::class, 'call'];
    $u->result_headers = [HubspotAnalyticsResultHeaders::class, 'call'];
    $u->transform_request = [HubspotAnalyticsTransformRequest::class, 'call'];
    $u->transform_response = [HubspotAnalyticsTransformResponse::class, 'call'];
});
